parameters:
- name: dockerRepo # name of the parameter; required
  type: string # data type of the parameter; required
  default: ''

jobs:
- job: Build

  pool:
    vmImage: ubuntu-latest

  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'docker hub'
      repository: ${{ parameters.dockerRepo }}
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
